version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: equitie-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - equitie-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: equitie-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - equitie-network
    profiles:
      - debug

volumes:
  redis-data:
    name: equitie-redis-data

networks:
  equitie-network:
    name: equitie-network
    driver: bridge